"""Load Stream Network phase (fishpass/requirements/requirements.md).

Creates <output_schema>.aoi and <output_schema>.streams as copies of the relevant
chyf_raw.aoi / chyf_raw.flowpath rows for the plan's aoi selection. <output_schema>.streams is
the single working/output table for the rest of the run -- see requirements.md's "Load Stream
Network" section for why there is no separate flowpath copy.
"""

import sys

from db import quote_ident

STREAMS_FIELDS = (
	"id", "aoi_id", "ef_type", "ef_subtype", "rank", "length",
	"from_nexus_id", "to_nexus_id", "ecatchment_id", "mainstem_id",
	"graph_id", "is_isolated", "strahler_order", "geometry",
)


def get_source_srid(cursor):
	cursor.execute(
		"SELECT ST_SRID(geometry) FROM chyf_raw.flowpath WHERE geometry IS NOT NULL LIMIT 1"
	)
	row = cursor.fetchone()
	if row is None or row[0] is None:
		sys.exit("Could not determine SRID from chyf_raw.flowpath -- is the table empty?")
	return row[0]


def resolve_workunit_aoi_ids(cursor, short_names):
	"""Resolve chyf_raw.aoi.short_name values to ids. Exits if any short_name doesn't resolve
	(typo protection), matching gradient_barriers' resolve_aois."""

	cursor.execute("SELECT id, short_name FROM chyf_raw.aoi WHERE short_name = ANY(%s)", (short_names,))
	rows = cursor.fetchall()
	found = {short_name: aoi_id for aoi_id, short_name in rows}
	missing = [s for s in short_names if s not in found]
	if missing:
		sys.exit(f"Could not resolve AOI short_name(s) in chyf_raw.aoi: {', '.join(missing)}")
	return [found[s] for s in short_names]


def resolve_province_aoi_ids(cursor, province_codes):
	"""Resolve province/territory codes to every chyf_raw.aoi id whose province_territory_code
	overlaps the requested list -- i.e. any workunit that intersects the provincial/territory
	boundary, per docs/decisions.md's "Province Territory Code Filtering" decision.

	Requires chyf_raw.aoi.province_territory_code (varchar[]) -- the prerequisite noted in
	docs/decisions.md.
	"""

	cursor.execute(
		"SELECT id FROM chyf_raw.aoi WHERE province_territory_code && %s::varchar[]",
		(province_codes,),
	)
	aoi_ids = [row[0] for row in cursor.fetchall()]
	if not aoi_ids:
		sys.exit(f"No AOIs found for province/territory code(s): {', '.join(province_codes)}")
	return aoi_ids


def resolve_aoi_ids(cursor, aoi_kind, aoi_value):
	"""Return the list of chyf_raw.aoi ids to copy for this plan's aoi selection, or None for
	aoi.workunit == 'all' (meaning: copy everything, no filter needed)."""

	if aoi_kind == "workunit":
		if aoi_value == "all":
			return None
		return resolve_workunit_aoi_ids(cursor, aoi_value)
	if aoi_kind == "province":
		return resolve_province_aoi_ids(cursor, aoi_value)
	raise ValueError(f"Unsupported aoi_kind: {aoi_kind!r}")  # upstream_of rejected earlier in model_plan


def init_output_schema(cursor, output_schema):
	"""Drop (if it exists) and recreate the output schema, per requirements.md's Initialize step.
	Output schemas are fully generated by this tool each run, so unlike gradient_barriers'
	support.gradient_barriers table, there's no manual-edit content to preserve/archive."""

	schema_ident = quote_ident(output_schema)
	cursor.execute(f"DROP SCHEMA IF EXISTS {schema_ident} CASCADE;")
	cursor.execute(f"CREATE SCHEMA {schema_ident};")


def create_aoi_table(cursor, output_schema):
	cursor.execute(f"""
		CREATE TABLE {quote_ident(output_schema)}.aoi (
			id uuid PRIMARY KEY,
			short_name varchar,
			province_territory_code varchar[]
		);
	""")


def create_streams_table(cursor, output_schema, srid):
	cursor.execute(f"""
		CREATE TABLE {quote_ident(output_schema)}.streams (
			id uuid PRIMARY KEY,
			aoi_id uuid,
			ef_type smallint,
			ef_subtype smallint,
			rank int,
			length double precision,
			from_nexus_id uuid,
			to_nexus_id uuid,
			ecatchment_id uuid,
			mainstem_id uuid,
			graph_id int,
			is_isolated boolean,
			strahler_order int,
			effective_length double precision,
			segment_gradient double precision,
			species_stats jsonb,
			lifecycle_stats jsonb,
			geometry geometry(LineStringZM, {srid}) NOT NULL
		);
	""")

def create_indexes(cursor, output_schema):
	cursor.execute(
		f"CREATE INDEX streams_geometry_idx ON {quote_ident(output_schema)}.streams USING gist (geometry);"
	)
	cursor.execute(
		f"CREATE INDEX streams_graph_id_idx ON {quote_ident(output_schema)}.streams (graph_id);"
	)
	cursor.execute(
		f"CREATE INDEX streams_aoi_id_idx ON {quote_ident(output_schema)}.streams (aoi_id);"
	)

def copy_aois(cursor, output_schema, aoi_ids):
	schema_ident = quote_ident(output_schema)
	if aoi_ids is None:
		cursor.execute(f"""
			INSERT INTO {schema_ident}.aoi (id, short_name, province_territory_code)
			SELECT id, short_name, province_territory_code FROM chyf_raw.aoi;
		""")
	else:
		cursor.execute(f"""
			INSERT INTO {schema_ident}.aoi (id, short_name, province_territory_code)
			SELECT id, short_name, province_territory_code FROM chyf_raw.aoi WHERE id = ANY(%s);
		""", (aoi_ids,))
	return cursor.rowcount


def copy_streams(cursor, output_schema, aoi_ids):
	schema_ident = quote_ident(output_schema)
	fields = ", ".join(STREAMS_FIELDS)
	if aoi_ids is None:
		cursor.execute(f"""
			INSERT INTO {schema_ident}.streams ({fields})
			SELECT {fields} FROM chyf_raw.flowpath;
		""")
	else:
		cursor.execute(f"""
			INSERT INTO {schema_ident}.streams ({fields})
			SELECT {fields} FROM chyf_raw.flowpath WHERE aoi_id = ANY (%s);
		""", (aoi_ids,))
	return cursor.rowcount


def load_stream_network(conn, cursor, plan):
	"""Run the full Load Stream Network phase for `plan` (see model_plan.load_model_plan).
	Must be called after init_output_schema. Returns the number of streams rows copied."""

	output_schema = plan["output_schema"]
	srid = get_source_srid(cursor)

	create_aoi_table(cursor, output_schema)
	create_streams_table(cursor, output_schema, srid)

	aoi_ids = resolve_aoi_ids(cursor, plan["aoi_kind"], plan["aoi_value"])

	aoi_count = copy_aois(cursor, output_schema, aoi_ids)
	stream_count = copy_streams(cursor, output_schema, aoi_ids)

	conn.commit()

	create_indexes(cursor, output_schema);

	print(f"Loaded {aoi_count} AOI(s) and {stream_count} stream edge(s) into {output_schema}.")
	return stream_count
