# Configuration for gradient_barriers computations.
# List of chyf_raw.aoi.short_name values to reprocess 
# Leave empty to recompute the entire network.
# see README.md for details.
#aoi:
#  workunit:
#     - 08MF001
#     - 08MG001
